name: Build

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Windows Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install gcc-mingw-w64-x86-64
    - run: curl https://files.eqela.com/eqelart/6.x/eqelart-6.0.9_linux.zip -o eqela.zip && mkdir eqela && cd eqela && unzip ../eqela.zip && rm ../eqela.zip && cd ..
    - run: PATH="`pwd`/eqela:$PATH" make CROSSTARGET="win32" -C src
  build-linux:
    name: Linux Build
    runs-on: ubuntu-18.04
    container: alpine:3.11.6
    steps:
    - uses: actions/checkout@v1
    - run: apk add --update alpine-sdk openssl-dev openssl-libs-static
    - run: curl https://files.eqela.com/eqelart/6.x/eqelart-6.0.9_linux.zip -o eqela.zip && mkdir eqela && cd eqela && unzip ../eqela.zip && rm ../eqela.zip && cd ..
    - run: PATH="`pwd`/eqela:$PATH" make STATIC_BUILD="yes" -C src
  build-macos:
    name: MacOS Build
    runs-on: macOS-10.15
    steps:
    - uses: actions/checkout@v1
    - run: curl https://files.eqela.com/eqelart/6.x/eqelart-6.0.9_macos.zip -o eqela.zip && mkdir eqela && cd eqela && unzip ../eqela.zip && rm ../eqela.zip && cd ..
    - run: PATH="`pwd`/eqela:$PATH" make -C src
